//! gRPC wire contracts for the EV concierge plane.
//!
//! The single source of truth for service-to-service communication on the
//! user/identity + platform plane. The proto files under `proto/concierge/v1/`
//! are authored here; `build.rs` compiles them with tonic into client **and**
//! server stubs on every `cargo build`.
//!
//! Consumption:
//! - The `concierge` runner (modular monolith) uses the **server** stubs
//!   (`concierge::v1::*_server`) to mount its auth/directory/notification/log
//!   modules.
//! - `evconcierge_auth` uses the `AuthService` stubs to serve its issuance routes.
//! - Other service repos add this crate as a git dependency for the **client**
//!   stubs, and `evconcierge_auth` for the verification flow.

/// Generated tonic code for the `concierge.v1` proto package (clients + servers +
/// message types), pulled in via `tonic::include_proto!("concierge.v1")`.
pub mod concierge {
	pub mod v1 {
		// Generated by tonic-build; not ours to lint.
		#![allow(clippy::all, clippy::pedantic)]
		tonic::include_proto!("concierge.v1");
	}
}
